#!/bin/bash

mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/brawlback-dolphin.svg $HOME/.local/share/icons/hicolor/scalable/apps
mkdir -p $HOME/.local/share/brawlback-dolphin && cp -R $APPDIR/usr/share/brawlback-dolphin $HOME/.local/share/

GITVER=$(wget -qO- https://www.github.com/FlowerGirlSmug/Project-Plus-Dolphin/releases/latest | grep '<p>DOLPHIN' | awk '{print $NF}' | cut -d '<' -f 1)
APPVER=$(cat $APPDIR/version.txt)

if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched "$@"
elif [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/AppRun-patched "$@"
else
	$APPDIR/update.sh "$@"
fi
